### ISSUE TITLE
Occur E157 when installing by dein

### ISSUE THREAD

**Issue by sigref** [neoclide/coc-denite#7]
When install or update with dein, E157 occurs.

# Message
```
[dein] Update started: (2020/06/24 20:26:42)
[dein] Updated plugins:
[dein]   coc-denite(1 change)
[dein]   coc.nvim(1 change)
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "CocLocationsChange" in file /Users/USERNAME/.cache/dein/.cache/
init.vim/.dein/doc/coc.txt
[dein] function <lambda>1[1]..dein#install#_polling[7]..<SNR>37_install_async[9]..<SNR>37_done[9]..d
ein#install#_recache_runtimepath[19]..<SNR>37_helptags, line 12
[dein] Done: (2020/06/24 20:27:00)
```

# Toml for dein
```toml
[[plugins]]
  repo = 'neoclide/coc.nvim'
  rev = 'release'
  merged = 0

[[plugins]]
  repo = 'neoclide/coc-denite'
```

# System
* macOS 10.15.5
* Ubuntu 18.04 on WSL

# Vim version
* neovim 0.4.3
